import * as fs from 'fs';
import * as path from 'path';

const tokensPath = path.join(__dirname, 'tokens.json');
const distDir = path.join(__dirname, '../dist');

if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// ─── Helpers ───

// Convert hex to Dart Color format: #8b5cf6 -> 0xFF8B5CF6
// For rgba() strings, use transparent black as fallback (Flutter handles opacity separately)
function toDartColor(hex: string): string {
  if (hex.startsWith('rgba') || hex.startsWith('rgb')) {
    // Extract hex approximation for Flutter — alpha handled via opacity in widgets
    return `Color(0x00000000)`;
  }
  return `Color(0xFF${hex.replace('#', '').toUpperCase()})`;
}

// ─── 1. Generate Tailwind Config Preset ───

const tailwindJs = `// Automatically generated by @titanhub/theme
module.exports.themePreset = {
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.colors, null, 2)},
      borderRadius: ${JSON.stringify(
        Object.fromEntries(Object.entries(tokens.radii).map(([k, v]) => [k, `${v}px`])),
        null,
        2
      )},
      boxShadow: ${JSON.stringify(tokens.shadows, null, 2)},
      transitionTimingFunction: {
        'out': '${tokens.animation.easeOut}',
        'in-out': '${tokens.animation.easeInOut}',
        'spring': '${tokens.animation.easeSpring}',
      },
      transitionDuration: {
        'fast': '${tokens.animation.durationFast}ms',
        'normal': '${tokens.animation.durationNormal}ms',
        'slow': '${tokens.animation.durationSlow}ms',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        'mono': ['Berkeley Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
    }
  }
};
`;

const tailwindDts = `export declare const themePreset: any;\n`;

fs.writeFileSync(path.join(distDir, 'tailwind-preset.js'), tailwindJs);
fs.writeFileSync(path.join(distDir, 'tailwind-preset.d.ts'), tailwindDts);

// ─── 2. Generate Flutter Dart Class ───

let dartContent = `// Automatically generated by @titanhub/theme
import 'dart:ui';

class AppTheme {
  // Colors
`;
for (const [key, value] of Object.entries(tokens.colors)) {
  dartContent += `  static const Color ${key} = ${toDartColor(value as string)};\n`;
}

dartContent += `\n  // Animations\n`;
for (const [key, value] of Object.entries(tokens.animation)) {
  if (typeof value === 'number') {
    dartContent += `  static const Duration ${key} = Duration(milliseconds: ${value});\n`;
  }
}

dartContent += `\n  // Radii\n`;
for (const [key, value] of Object.entries(tokens.radii)) {
  dartContent += `  static const double radius${key.toUpperCase()} = ${value}.0;\n`;
}

dartContent += `}\n`;

fs.writeFileSync(path.join(distDir, 'app_theme.dart'), dartContent);

// Copy to Flutter mobile app if it exists
const mobileThemeDir = path.join(__dirname, '../../../apps/mobile/lib/core/theme');
if (fs.existsSync(mobileThemeDir)) {
  fs.writeFileSync(path.join(mobileThemeDir, 'app_theme.dart'), dartContent);
  console.log('✅ Synchronized app_theme.dart to apps/mobile/');
}

// ─── 3. Generate CSS Custom Properties ───

let cssContent = `/* Automatically generated by @titanhub/theme */
:root {\n`;

// Colors as CSS variables
cssContent += `  /* Colors */\n`;
for (const [key, value] of Object.entries(tokens.colors)) {
  const cssVar = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  cssContent += `  --color-${cssVar}: ${value};\n`;
}

// Shadows
cssContent += `\n  /* Shadows */\n`;
for (const [key, value] of Object.entries(tokens.shadows)) {
  const cssVar = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  cssContent += `  --shadow-${cssVar}: ${value};\n`;
}

// Animation
cssContent += `\n  /* Animation */\n`;
for (const [key, value] of Object.entries(tokens.animation)) {
  const cssVar = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  if (typeof value === 'number') {
    cssContent += `  --duration-${cssVar}: ${value}ms;\n`;
  } else {
    cssContent += `  --ease-${cssVar}: ${value};\n`;
  }
}

// Radii
cssContent += `\n  /* Radii */\n`;
for (const [key, value] of Object.entries(tokens.radii)) {
  const cssVar = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  cssContent += `  --radius-${cssVar}: ${value}px;\n`;
}

// Typography
cssContent += `\n  /* Typography */\n`;
cssContent += `  --font-sans: ${tokens.typography.fontSans};\n`;
cssContent += `  --font-mono: ${tokens.typography.fontMono};\n`;
for (const [key, value] of Object.entries(tokens.typography)) {
  if (typeof value === 'object' && value !== null) {
    const v = value as any;
    cssContent += `  --text-${key}-size: ${v.size};\n`;
    cssContent += `  --text-${key}-weight: ${v.weight};\n`;
    cssContent += `  --text-${key}-line-height: ${v.lineHeight};\n`;
    cssContent += `  --text-${key}-letter-spacing: ${v.letterSpacing};\n`;
  }
}

cssContent += `}\n`;

fs.writeFileSync(path.join(distDir, 'theme.css'), cssContent);

// ─── 4. Exports ───

fs.writeFileSync(
  path.join(distDir, 'index.js'),
  `module.exports = require('./tailwind-preset');\n`
);
fs.writeFileSync(path.join(distDir, 'index.d.ts'), `export * from './tailwind-preset';\n`);

console.log('✅ Tokens compiled successfully to dist/ (colors, shadows, typography, radii, CSS vars)');
