import * as fs from 'fs';
import * as path from 'path';

const tokensPath = path.join(__dirname, 'tokens.json');
const distDir = path.join(__dirname, '../dist');

if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// 1. Generate Tailwind Config Preset
const tailwindJs = `// Automatically generated by @titanhub/theme
module.exports.themePreset = {
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.colors, null, 2)},
      borderRadius: ${JSON.stringify(
        Object.fromEntries(Object.entries(tokens.radii).map(([k, v]) => [k, `${v}px`])),
        null,
        2
      )},
    }
  }
};
`;

const tailwindDts = `export declare const themePreset: any;\n`;

fs.writeFileSync(path.join(distDir, 'tailwind-preset.js'), tailwindJs);
fs.writeFileSync(path.join(distDir, 'tailwind-preset.d.ts'), tailwindDts);

// 2. Generate Flutter Dart Class
// Convert hex to Dart Color format: #8b5cf6 -> 0xFF8B5CF6
function toDartColor(hex: string) {
  return `Color(0xFF${hex.replace('#', '').toUpperCase()})`;
}

let dartContent = `// Automatically generated by @titanhub/theme
import 'dart:ui';

class AppTheme {
  // Colors
`;
for (const [key, value] of Object.entries(tokens.colors)) {
  dartContent += `  static const Color ${key} = ${toDartColor(value as string)};\n`;
}

dartContent += `\n  // Animations\n`;
for (const [key, value] of Object.entries(tokens.animation)) {
  dartContent += `  static const Duration ${key} = Duration(milliseconds: ${value});\n`;
}

dartContent += `\n  // Radii\n`;
for (const [key, value] of Object.entries(tokens.radii)) {
  dartContent += `  static const double radius${key.toUpperCase()} = ${value}.0;\n`;
}

dartContent += `}\n`;

fs.writeFileSync(path.join(distDir, 'app_theme.dart'), dartContent);

// Copy to Flutter mobile app if it exists
const mobileThemeDir = path.join(__dirname, '../../../apps/mobile/lib/core/theme');
if (fs.existsSync(mobileThemeDir)) {
  fs.writeFileSync(path.join(mobileThemeDir, 'app_theme.dart'), dartContent);
  console.log('✅ Synchronized app_theme.dart to apps/mobile/');
}

// Also create an index.js to export the tailwind preset
fs.writeFileSync(
  path.join(distDir, 'index.js'),
  `module.exports = require('./tailwind-preset');\n`
);
fs.writeFileSync(path.join(distDir, 'index.d.ts'), `export * from './tailwind-preset';\n`);

console.log('✅ Tokens compiled successfully to dist/');
